### ISSUE TITLE
Add life-points

### ISSUE THREAD

**Issue by fry-** [fry-/juck#1]
Add some initial life points, I would say 5 for the game start. 
After surviving 30 sec (or similar value) you get 1 more life added. 
If you hit an obstacle while not being in ghost mode (half transparent player) you lose a life.

preferably the display of amount of life is shown as text, so we don't get into trouble when a good player sums up life (if we would make a bar or display it with little hearts in a row, it could easily exceed the expected amount because the player gets an additional life every 30sec).

**Comment by alketii** [comment]
Can you choose a font for this ? including color & size.

**Comment by alketii** [comment]
Fix attempt with e8fddb16148543e00d9b28fafb921d6c302d46e0 and a5df2b42ff6f65be6f8ebaa3983c2aa8bb038ee1

**Comment by fry-** [comment]
@alketii nice!
